protoc --go_out=. --go-grpc_out=. golang/proto/auth/auth.proto
protoc --go_out=. --go-grpc_out=. golang/proto/transaction/transaction.proto
protoc --go_out=. --go-grpc_out=. golang/proto/wallet/wallet.proto
protoc --go_out=. --go-grpc_out=. golang/proto/user/user.proto

